# Generated by Django 4.1.7 on 2023-02-16 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='training_type',
            field=models.CharField(blank=True, choices=[('Szkolenie', 'Szkolenie'), ('G1/2/3', 'G1/2/3')], max_length=10),
        ),
    ]
