# Generated by Django 4.1.7 on 2023-02-16 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgapp', '0002_training_training_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='training_type',
            field=models.CharField(choices=[('Szkolenie', 'Szkolenie'), ('G1/2/3', 'G1/2/3')], max_length=10),
        ),
    ]
