# Generated by Django 4.1.7 on 2023-02-16 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgapp', '0004_training_venue_alter_training_training_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='training_type',
            field=models.CharField(blank=True, choices=[('Szkolenie', 'Szkolenie'), ('G1/2/3', 'G1/2/3')], max_length=40),
        ),
        migrations.AlterField(
            model_name='training',
            name='venue',
            field=models.CharField(choices=[('Inne...', 'Inne...')], max_length=20),
        ),
    ]
