# Generated by Django 4.1.7 on 2023-02-17 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgapp', '0011_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='aprrove',
            field=models.BooleanField(default=True),
        ),
    ]
