# Generated by Django 4.1.7 on 2023-02-17 18:14

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('sgapp', '0013_persons_delete_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persons',
            name='phone',
            field=phone_field.models.PhoneField(max_length=31),
        ),
    ]
