# Generated by Django 4.1.7 on 2023-02-17 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sgapp', '0014_alter_persons_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persons',
            name='training',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sgapp.training'),
        ),
    ]
