# Generated by Django 4.1.7 on 2023-02-19 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sgapp', '0017_delete_book'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persons',
            options={'verbose_name_plural': 'Ludziki'},
        ),
    ]
